#!/usr/bin/env python


def update_if_true(execute:bool, to_execute: callable):
    to_execute()


def echo():
    print("echooooo")

def ok():
    print("okkkkkk")

update_if_true(True, echo)
update_if_true(False, ok)
